from pathlib import Path
import re,shutil,sys
r=Path.cwd(); hp=r/'src/app/app.component.html'; sp=r/'src/app/app.component.scss'; tp=r/'src/app/app.component.ts'; ip=r/'src/index.html'
if not all(p.exists() for p in (hp,sp,tp,ip,r/'public/images')): sys.exit('Uruchom skrypt w katalogu glownym projektu.')
a=Path(__file__).parent/'assets'
for n in ('wedding-rings.png','ania-anime.png','karol-anime.png'): shutil.copy2(a/n,r/'public/images'/n)
h=hp.read_text(encoding='utf-8').replace('28 września 2026','26 września 2026').replace('28.09.2026','26.09.2026')
rings='''\n      <div class="rings-photo" aria-hidden="true">\n        <img src="/images/wedding-rings.png" alt="">\n        <span class="rings-photo__shine"></span>\n      </div>'''
h,n=re.subn(r'\s*<div class="(?:bands|rings-photo)" aria-hidden="true">.*?</div>',rings,h,count=1,flags=re.S)
if not n: sys.exit('Nie znaleziono obraczek.')
h,n=re.subn(r'(<div class="profile-card">\s*)<img[^>]+>(\s*<div class="profile-card__caption">).*?(</div>)',r'\1<img src="/images/karol.jpg" alt="Portret Karola">\2<strong>Karol</strong><span>To wygląda obiecująco ✨</span>\3',h,count=1,flags=re.S)
if not n: sys.exit('Nie znaleziono karty Match.')
k='''\n    <section class="kiss-scene chapter--center">\n      <div class="kiss-stage"><div class="anime-character anime-character--ania"><img src="/images/ania-anime.png" alt="Stylizowana postać Ani"></div><div class="kiss-burst" aria-hidden="true"><span>♥</span><i>✦</i><b>♥</b></div><div class="anime-character anime-character--karol"><img src="/images/karol-anime.png" alt="Stylizowana postać Karola"></div></div>\n      <p class="kicker" data-reveal>A później…</p><h2 data-reveal>pojawiła się iskra.</h2><p data-reveal>I od tego momentu wszystko potoczyło się już całkiem naturalnie.</p>\n    </section>\n\n    '''
h,n=re.subn(r'\s*<section class="kiss-scene chapter--center">.*?</section>\s*(?=<section class="date-scene">)',k,h,count=1,flags=re.S)
if not n: sys.exit('Nie znaleziono sceny buziaka.')
hp.write_text(h,encoding='utf-8'); ip.write_text(ip.read_text(encoding='utf-8').replace('28.09.2026','26.09.2026'),encoding='utf-8')
t=tp.read_text(encoding='utf-8')
# Replace code from first rings .from until intro copy .from, regardless of V1/V2.
t,n=re.subn(r"\n\s*\.from\('\.(?:band--gold|rings-photo)'.*?(?=\n\s*\.from\('\.intro__copy)","\n        .from('.rings-photo', { y: 55, scale: .62, rotation: -7, opacity: 0, duration: 1.9, ease: 'power3.out' }, '-=.6')\n        .to('.rings-photo', { scale: 1.055, duration: .75, yoyo: true, repeat: 1 })\n        .fromTo('.rings-photo__shine', { xPercent: -170, opacity: 0 }, { xPercent: 190, opacity: .9, duration: 1.15 }, '-=1.15')",t,count=1,flags=re.S)
if not n: sys.exit('Nie znaleziono animacji obraczek.')
t=re.sub(r"\n\s*gsap\.timeline\(\{ scrollTrigger: \{ trigger: '\.kiss-scene'.*?;\n",'\n',t,flags=re.S)
kt="""\n      gsap.timeline({ scrollTrigger: { trigger: '.kiss-scene', start: 'top 68%', once: true } })\n        .from('.anime-character--ania', { xPercent: -160, opacity: 0, duration: 1.35 })\n        .from('.anime-character--karol', { xPercent: 160, opacity: 0, duration: 1.35 }, '<')\n        .to('.anime-character--ania', { xPercent: 34, rotation: 3, duration: 1.15 })\n        .to('.anime-character--karol', { xPercent: -34, rotation: -3, duration: 1.15 }, '<')\n        .from('.kiss-burst > *', { scale: 0, opacity: 0, duration: .65, stagger: .12, ease: 'back.out(2)' }, '-=.18');\n\n"""
m="      gsap.timeline({ scrollTrigger: { trigger: '.date-scene'"
if m not in t: sys.exit('Nie znaleziono animacji daty.')
tp.write_text(t.replace(m,kt+m,1),encoding='utf-8')
s=sp.read_text(encoding='utf-8'); s=re.sub(r'\n/\* v3 assets and animated couple \*/.*\Z','',s,flags=re.S); s+='''\n\n/* v3 assets and animated couple */\n.rings-photo{position:absolute;top:9%;display:grid;place-items:center;width:min(92vw,42rem);filter:drop-shadow(0 1.5rem 1.5rem #000c);overflow:hidden}.rings-photo img{display:block;width:100%;height:auto;object-fit:contain;mix-blend-mode:normal}.rings-photo__shine{position:absolute;inset:-20%;background:linear-gradient(105deg,transparent 38%,#fff8d9cc 48%,transparent 58%);transform:translateX(-170%) rotate(10deg);mix-blend-mode:screen;filter:blur(6px)}.kiss-stage{grid-column:1/-1;position:relative;display:grid;grid-template-columns:1fr 1fr;align-items:end;width:min(96vw,64rem);height:clamp(20rem,64vw,39rem);margin-bottom:1.8rem}.anime-character{z-index:1;display:flex;align-items:flex-end;height:100%}.anime-character img{display:block;width:clamp(15rem,46vw,32rem);max-width:none;filter:drop-shadow(0 1.2rem 1.2rem #000a)}.anime-character--ania{justify-content:flex-end}.anime-character--karol{justify-content:flex-start}.anime-character--karol img{transform:scaleX(-1)}.kiss-burst{position:absolute;z-index:3;left:50%;top:33%;transform:translate(-50%,-50%);width:8rem;height:8rem;color:#ee6680}.kiss-burst span{position:absolute;left:37%;top:28%;font-size:3.8rem}.kiss-burst i{position:absolute;left:4%;top:8%;color:#f4c36f;font-size:2rem}.kiss-burst b{position:absolute;right:3%;bottom:5%;font-size:1.8rem}@media(max-width:600px){.rings-photo{top:13%;width:100vw}.intro__copy{margin-top:14rem}.kiss-stage{width:118vw;height:24rem}.anime-character img{width:17rem}.kiss-burst{top:36%;transform:translate(-50%,-50%) scale(.72)}}\n'''; sp.write_text(s,encoding='utf-8')
print('OK: V3 zastosowane. Uruchom npm run build.')
